force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Equipment</fullName>
                <default>true</default>
                <label>Equipment</label>
            </value>
            <value>
                <fullName>Furniture</fullName>
            </value>
            <value>
                <fullName>Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ForResViewCont.cls
public with sharing class ForResViewCont {

    public List<selectOption> options { get; set; }
    public List<Resource__c> resources { get; set; }
    public String listValue { get; set; }
    
    public ForResViewCont() {
        options = new List<selectOption>();
        options.add(new selectOption('Equipment','Equipment'));
        options.add(new selectOption('Furniture','Furniture'));
        options.add(new selectOption('Car','Car'));
    } 
    
    public PageReference changeResources() {
        resources = [SELECT Id, Name FROM Resource__c WHERE Type__c = :this.listValue LIMIT 10000];
        return null;
    }

}